### PR TITLE
created test controller

### PR DESCRIPTION
**Pull request by AlenaNguyen**

### CODE REVIEW

**Review by TaylerUva — COMMENTED** [review]
Were you able to test this in sim? Curious if the swapping between modes breaks it. Youll be able to check by running test mode, then teleop and seeing if you can move from None state to PrepSpeaker state

**Comment by AlenaNguyen** [comment]
> Were you able to test this in sim? Curious if the swapping between modes breaks it. Youll be able to check by running test mode, then teleop and seeing if you can move from None state to PrepSpeaker state

It's hard to tell because we have additional checks within the state commands (ex. we only set the RobotState to PREP_SPEAKER if its previous state was STORE_FEEDER). So even in test mode, I can't tell if the robot is doing the thing (the state just stays at NONE).
But I think something broke: when I switch from test to teleop, I can't intake anymore even though I'm in the NONE state 🙃 (disabling and going straight to teleop works though)

**Comment by TaylerUva** [comment]
> > Were you able to test this in sim? Curious if the swapping between modes breaks it. Youll be able to check by running test mode, then teleop and seeing if you can move from None state to PrepSpeaker state
> 
> It's hard to tell because we have additional checks within the state commands (ex. we only set the RobotState to PREP_SPEAKER if its previous state was STORE_FEEDER). So even in test mode, I can't tell if the robot is doing the thing (the state just stays at NONE). But I think something broke: when I switch from test to teleop, I can't intake anymore even though I'm in the NONE state 🙃 (disabling and going straight to teleop works though)

So does TeleOp -> Disable -> Test -> Disable -> TeleOp -> Disable -> Test -> ... work? or just on first boot to teleop?

**Comment by AlenaNguyen** [comment]
> So does TeleOp -> Disable -> Test -> Disable -> TeleOp -> Disable -> Test -> ... work? or just on first boot to teleop?

Yes, it only works on the first boot of teleop.... and then it dies

**Comment by TaylerUva** [comment]
> Yes, it only works on the first boot of teleop.... and then it dies

Let's try moving `new SN_XboxController(mapControllers.DRIVER_USB);` (both controllers) inside of their respective configure methods. We may need to remove the `final` keyword

**Review by TaylerUva — APPROVED** [review]
Wonderful :D

**Pull request merged**
