### PR TITLE
Basic Shooter Changes

### LINKED ISSUE #76: Add prep backwards sub

### LINKED ISSUE #78: Add current limiting to elevator, climber and pivot
So we don't break it D:

### LINKED ISSUE #82: Shoot pivot updates
- [ ] Lower P
- [ ] Update gear ratio (The ratio used to be 70.2:1. It’s now 58.5)

### PR DESCRIPTION
**Pull request by alicekuznetsov**
Closes #82

### CODE REVIEW

**Comment by alicekuznetsov** [comment]
Okay so i found a bug 😨
When we go from PrepAmp to StoreFeeder, the elevator currently doesn't go down. However, if we were to add it into StoreFeeder for it to go down, then we would have to lower and then raise the elevator for going between positions like backwards sub and prep amp 
thoughts? @TaylerUva  @Alenguye582

**Comment by alicekuznetsov** [comment]
also i probably most definetly broke either prep none or store feeder in this pr so please send help 🙏

**Comment by AlenaNguyen** [comment]
> Okay so i found a bug 😨 When we go from PrepAmp to StoreFeeder, the elevator currently doesn't go down. However, if we were to add it into StoreFeeder for it to go down, then we would have to lower and then raise the elevator for going between positions like backwards sub and prep amp thoughts? @TaylerUva @Alenguye582

😰 hmmm so is the problem collisions or just having that extra step of lowering then raising? I don't think that extra step would be a big problem.

**Comment by alicekuznetsov** [comment]
> 😰 hmmm so is the problem collisions or just having that extra step of lowering then raising? I don't think that extra step would be a big problem.

The extra step is actually a pretty big problem. It removes the entire point of Target States, since the elevator has to wait for the shooter to move down,completely go down, and then go BACK to where it just was (given that we were prepped)

**Comment by TaylerUva** [comment]
> The extra step is actually a pretty big problem. It removes the entire point of Target States, since the elevator has to wait for the shooter to move down,completely go down, and then go BACK to where it just was (given that we were prepped)
> 

Maybe the prep states should determine where the elevator lives? Prep None brings it down? This has the added benefit of not waiting for stuff when intaking. I also notices intaking moves the pivot angle. This should only occur when we are "out of bounds" for intaking.

**Review by TaylerUva — APPROVED** [review]

**Comment by TaylerUva** [comment]
Approved but PR is draft @ACat701 so it's not merged

**Pull request merged**
